### ISSUE TITLE
Upload hirte builder container to quay

### ISSUE THREAD

**Issue by Yarboa** [engelmi/hirte#140]
Use image from quay for hirte build and tests

## Desctription

https://github.com/containers/hirte/pull/104#discussion_r1100281572

##Prepare and upload image to libpod registry
quay.io/yarboa/hirte-builder shuold be created under quay.io/libpod 
Note: Consider opening new enterprise hirte under quay? 

These line could be pulled from quay registry
https://github.com/containers/hirte/blob/main/.github/workflows/build.yml#L14-L29

replace this 
```
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
```      
with 
```
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/libpod/hirte-builder
 ```     
 Name should be considered more seriously
